version: '3'

services:
  postgres:
    image: postgres:10.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=zyres
      - POSTGRES_USER=zyres
      - POSTGRES_DB=car

  car:
    image: de.kreutz.michael/car-shop
    ports:
    - "8080:8080"
    depends_on:
    - postgres
    environment:
    - SPRING_PROFILES_ACTIVE=docker
